version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  branch_tag_check:
    steps:
      - run:
          name: check if branch AND tag conditions are met
          command: |
            if [[ ! ($CIRCLE_BRANCH == "only-this-branch" && \
              $CIRCLE_TAG == "only-this-tag") ]]
            then
              exit 1
            else
              echo "rest of jobs can proceed"
            fi

  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: echo 'export CODACY_PROJECT_TOKEN' >> $CODACY_PROJECT_TOKEN	
      - run: npm run test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - branch_tag_check
      - build
      - test:
          requires:
            - build
      - deploy:
          type: approval
          requires:
            - test
            - branch_tag_check